# Assign LD span for SNPs based on LD-decay within genomic windows

In [4]:
rm(list=ls())
library(tidyverse)
library(readxl)

# change these variables as needed
wdir = "/lustre/orion/syb111/proj-shared/Personal/abeyratnecr/switchgrass/sub_proj/snp2geneLD"
snplist_fn = paste0(wdir, "/switchgrass_vessel_num_SNPs.xlsx")
window_list_fn = paste0(wdir, "/pw_ld/1000000_500000.bed") # filename of the bed file with genomic intervals for LD estimation

setwd(wdir)

In [19]:
gwas_master_ss <- read_xlsx(path=snplist_fn, col_names=TRUE)
# dim(tmp_)
# str(tmp_)

In [42]:
# Input window list
windows <- read.table(window_list_fn, header=F)
colnames(windows) <- c('Chr', 'Start', 'End')
# dim(windows)
# head(windows)

# read the model fit and span values for intervals after modelling LD-decay
decay_fit <- NULL
missing_files <- NULL
missing_iterations <- NULL
for (i in 1:nrow(windows)) {
    filename <- paste0(wdir, '/pw_ld/', windows$Chr[i], '_', windows$Start[i], '_', windows$End[i], '.decay')
    if (file.exists(filename)) {
        tmp <- read.table(filename, header=T)
        decay_fit <- rbind(decay_fit, cbind(Chr=windows$Chr[i], Start=windows$Start[i], End=windows$End[i], tmp))
    } else {
        missing_files <- c(missing_files, filename)
        missing_iterations <- c(missing_iterations, i)
    }
}
decay_fit <- decay_fit %>% as.data.frame()
# stopifnot(nrow(decay_fit) == nrow(windows))

dim(decay_fit)
head(decay_fit)

[1] 1648    6

  Chr    Start   End     distance.span expected.ld mod_fit
1 Chr01K       0 1000000 9337          0.02307004  0.9549745
2 Chr01K  500000 1500000 7348          0.02111843  0.9777420
3 Chr01K 1000000 2000000 6390          0.01738335  0.9664553
4 Chr01K 1500000 2500000 6266          0.01746169  0.9510637
5 Chr01K 2000000 3000000 6849          0.01807289  0.9592801
6 Chr01K 2500000 3500000 6375          0.01840936  0.9583541

In [43]:
# Are there any missing files for the genomic interval LD estimation?
missing_iterations %>% length()
missing_iterations
# At this point check if there are missing LD estimates for genomic windows. Possible reason could be that script-3 did not run to completion

[1] 559

  [1]  249  388  444  450 1514 1518 1521 1522 1525 1526 1529 1530 1533 1534 1537
 [16] 1538 1541 1542 1543 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555
 [31] 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 [46] 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584 1585
 [61] 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598 1599 1600
 [76] 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612 1613 1614 1615
 [91] 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626 1627 1628 1629 1630
[106] 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640 1641 1642 1643 1644 1645
[121] 1646 1647 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1658 1659 1660
[136] 1661 1662 1663 1664 1665 1666 1667 1668 1669 1670 1671 1672 1673 1674 1675
[151] 1676 1677 1678 1679 1680 1681 1682 1683 1684 1685 1686 1687 1688 1689 1690
[166] 1691 1692 1693 1694 1695 1696 1697 1698 1699 1700 1701 1702 1703 1704 1705
[181] 1706 1707 1708 1709 1710 1711 1712 1713 1714 1715 1716 1717 1718 1719 1720
[196] 1721 1722 1723 1724 1725 1726 1727 1728 1729 1730 1731 1732 1733 1734 1735
[211] 1736 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750
[226] 1751 1752 1753 1754 1755 1756 1757 1758 1759 1760 1761 1762 1763 1764 1765
[241] 1766 1767 1768 1769 1770 1771 1772 1773 1774 1775 1776 1777 1778 1779 1780
[256] 1781 1782 1783 1784 1785 1786 1787 1788 1789 1790 1791 1792 1793 1794 1795
[271] 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806 1807 1808 1809 1810
[286] 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1821 1822 1823 1824 1825
[301] 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835 1836 1837 1838 1839 1840
[316] 1841 1842 1843 1844 1845 1846 1847 1848 1849 1850 1851 1852 1853 1854 1855
[331] 1856 1857 1858 1859 1860 1861 1862 1863 1864 1865 1866 1867 1868 1869 1870
[346] 1871 1872 1873 1874 1875 1876 1877 1878 1879 1880 1881 1882 1883 1884 1885
[361] 1886 1887 1888 1889 1890 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900
[376] 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915
[391] 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930
[406] 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945
[421] 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960
[436] 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975
[451] 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990
[466] 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005
[481] 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
[496] 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2032 2033 2034 2035
[511] 2036 2037 2038 2039 2040 2041 2042 2043 2044 2045 2046 2047 2048 2049 2050
[526] 2051 2052 2053 2054 2055 2056 2057 2058 2059 2060 2061 2062 2063 2064 2065
[541] 2066 2067 2068 2069 2070 2071 2072 2073 2074 2075 2076 2077 2078 2079 2080
[556] 2081 2082 2083 2084

In [44]:
head(decay_fit)

  Chr    Start   End     distance.span expected.ld mod_fit
1 Chr01K       0 1000000 9337          0.02307004  0.9549745
2 Chr01K  500000 1500000 7348          0.02111843  0.9777420
3 Chr01K 1000000 2000000 6390          0.01738335  0.9664553
4 Chr01K 1500000 2500000 6266          0.01746169  0.9510637
5 Chr01K 2000000 3000000 6849          0.01807289  0.9592801
6 Chr01K 2500000 3500000 6375          0.01840936  0.9583541

In [45]:
# assigning window spans for each of the SNPs based on overlap with genomic windows
unmatched_idx <- NULL
gwas_with_span <- NULL
for (i in 1:nrow(gwas_master_ss)) {
    tmp_decay_fit <- decay_fit %>% 
    filter(Chr==paste0('Chr', gwas_master_ss$Chr[i])) %>%
    mutate(snp_pos = gwas_master_ss$Pos[i]) %>%
    mutate(olap = ifelse(snp_pos >= Start & snp_pos <= End, 1, 0)) %>% 
    filter(olap == 1)
    # filter(Start <= gwas_master_ss$Pos[i] & End >= gwas_master_ss$Pos[i])

    if (nrow(tmp_decay_fit) == 0) {
        # SNP does not overlap with the window
        unmatched_idx = c(unmatched_idx, i)
        next
    } else if (nrow(tmp_decay_fit) == 1) {
        # SNP overlaps with one window
        span = tmp_decay_fit$distance.span[1]
        mod_fit = tmp_decay_fit$mod_fit[1]
    } else {
        # If SNP overlaps with more than one window taking the average
        span = round(mean(tmp_decay_fit$distance.span),0) 
        mod_fit = mean(tmp_decay_fit$mod_fit)
    }
    
    up_loc = gwas_master_ss$Pos[i] - span
    down_loc = gwas_master_ss$Pos[i] + span
    up_loc = ifelse(up_loc < 0, 0, up_loc)

    gwas_with_span <- rbind(gwas_with_span, cbind(gwas_master_ss[i,],
                                                  mod_fit=mod_fit,
                                                  span=span,
                                                  up_loc=up_loc,
                                                  down_loc=down_loc))
}

In [46]:
unmatched_idx %>% length()

[1] 0

In [47]:
dim(gwas_with_span)
# stopifnot(nrow(gwas_master_ss) == nrow(gwas_with_span)) # checking if all SNPs have assigned LD spans
gwas_with_span %>% head()

[1] 14 36

  gwas_model trait                 SNP             Chr Pos      P.value
1 FarmCPU    ihf.vessel_num.2023.1 Chr09N_23044526 09N 23044526 1.513442e-24
2 BLINK      ihf.vessel_num.2023.1 Chr09N_23044526 09N 23044526 3.518736e-14
3 FarmCPU    ihf.vessel_num.2023.1 Chr09N_23044526 09N 23044526 1.513442e-24
4 BLINK      ihf.vessel_num.2023.1 Chr09N_23044526 09N 23044526 3.518736e-14
5 BLINK      ihf.vessel_num.2023.1 Chr09N_28381027 09N 28381027 1.296128e-10
6 BLINK      ihf.vessel_num.2023.1 Chr09N_28381027 09N 28381027 1.296128e-10
  MAF       nobs H.B.P.Value  Effect    ⋯ Best.hit.arabi.name arabi.symbol
1 0.1853659 205  1.677293e-18 -2.023093 ⋯ AT5G03230.1         NA
2 0.1853659 205  3.899688e-08 -1.889314 ⋯ AT5G03230.1         NA
3 0.1853659 205  1.677293e-18 -2.023093 ⋯ NA                  NA
4 0.1853659 205  3.899688e-08 -1.889314 ⋯ NA                  NA
5 0.4268293 205  7.182260e-05 -1.197452 ⋯ AT1G03670.1         NA
6 0.4268293 205  7.182260e-05 -1.197452 ⋯ AT1G03670.1         NA
  arabi.defline                       Best.hit.rice.name rice.symbol
1 Protein of unknown function, DUF584 LOC_Os10g33990.1   NA
2 Protein of unknown function, DUF584 LOC_Os10g33990.1   NA
3 NA                                  NA                 NA
4 NA                                  NA                 NA
5 ankyrin repeat family protein       LOC_Os11g14570.2   NA
6 ankyrin repeat family protein       LOC_Os11g14570.1   NA
  rice.defline                                          mod_fit   span up_loc
1 DUF584 domain containing protein, putative, expressed 0.9762811 8757 23035769
2 DUF584 domain containing protein, putative, expressed 0.9762811 8757 23035769
3 NA                                                    0.9762811 8757 23035769
4 NA                                                    0.9762811 8757 23035769
5 expressed protein                                     0.9597586 7103 28373924
6 expressed protein                                     0.9597586 7103 28373924
  down_loc
1 23053283
2 23053283
3 23053283
4 23053283
5 28388130
6 28388130

In [49]:
# Write the selected hits.
write.csv(gwas_with_span, file=paste0(wdir, '/fsnps/gwas_with_span.csv'), row.names=F, quote=F)

In [50]:
# write the list of unique coordinates to find genes associated with coordinates
query_intervals <- gwas_with_span %>% dplyr::select(Chr, up_loc, down_loc) %>% distinct() %>% arrange(Chr, up_loc)
write.table(query_intervals, file=paste0(wdir, '/fsnps/query_intervals.bed'), col.names=F, row.names=F, quote=F, sep="\t")

In [52]:
query_intervals %>% mutate(span=down_loc-up_loc)

  Chr up_loc   down_loc span
1 09N 23035769 23053283 17514
2 09N 28373924 28388130 14206
3 09N 47830294 47843962 13668
4 09N 57579395 57595041 15646
5 09N 81607581 81620739 13158

In [ ]:
# END